# Generated by Django 4.2.7 on 2024-09-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('subject', models.CharField(max_length=155, verbose_name='Обьект')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='settings',
            name='image4',
            field=models.ImageField(default=1, upload_to='settings/', verbose_name='Фото 4'),
            preserve_default=False,
        ),
    ]
