# Generated by Django 4.2.7 on 2024-09-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_settings_run_title_1_settings_run_title_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='instagram',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='run_title_1',
            field=models.CharField(max_length=155, verbose_name='Бегающий текст - 1'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='run_title_2',
            field=models.CharField(max_length=155, verbose_name='Бегающий текст - 2'),
        ),
    ]
