# Generated by Django 4.2.7 on 2024-09-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_settings_instagram_alter_settings_run_title_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя специалиста')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('occupation', models.CharField(max_length=100, verbose_name='Профессия')),
                ('phone', models.TextField(max_length=100, verbose_name='Контактные данные')),
                ('email', models.CharField(max_length=100, verbose_name='Почта')),
                ('Nationality', models.CharField(max_length=100, verbose_name='Национальность')),
            ],
            options={
                'verbose_name_plural': 'Специалист',
            },
        ),
    ]
