# Generated by Django 4.2.7 on 2024-09-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_rename_nationality_about_person_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_direction', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('main_title', models.CharField(max_length=100, verbose_name='Что и для кого был сделан проект')),
                ('image_1', models.ImageField(upload_to='settings/', verbose_name='Фото 1')),
                ('image_2', models.ImageField(upload_to='settings/', verbose_name='Фото 2')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=100, verbose_name='Про сам проект')),
                ('сlient', models.CharField(max_length=100, verbose_name='Клиент')),
                ('duration', models.CharField(max_length=100, verbose_name='Срок разработки')),
                ('task', models.CharField(max_length=100, verbose_name='Какие направления были воздействованы')),
                ('budget', models.CharField(max_length=100, verbose_name='Бюджет')),
                ('project_type', models.CharField(max_length=100, verbose_name='Про сам проект')),
                ('tags', models.CharField(max_length=100, verbose_name='Теги')),
            ],
            options={
                'verbose_name_plural': 'Специалист',
            },
        ),
        migrations.AlterModelOptions(
            name='about_person',
            options={'verbose_name_plural': 'Специалиста'},
        ),
        migrations.AlterField(
            model_name='about_person',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Контактные данные'),
        ),
    ]
