# Generated by Django 4.2.7 on 2024-09-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_portfolio_alter_about_person_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='tags',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Про сам проект'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project_type',
            field=models.CharField(max_length=100, verbose_name='Тип проета'),
        ),
    ]
