# Generated by Django 4.2.7 on 2024-09-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_remove_portfolio_tags_alter_portfolio_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': 'Портфолио'},
        ),
    ]
