# Generated by Django 4.2.7 on 2024-09-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_alter_portfolio_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_name', models.CharField(max_length=100, verbose_name='Имя заголовка')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('quantity', models.CharField(max_length=100, verbose_name='Количество')),
                ('title_2', models.CharField(max_length=100, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name_plural': 'Факты',
            },
        ),
    ]
