# Generated by Django 4.2.7 on 2024-09-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_fuct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fuct',
            new_name='Fact',
        ),
    ]
