# Generated by Django 4.2.7 on 2024-09-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_awards_alter_portfolio_image_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expirience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Звание')),
                ('mini_title', models.CharField(max_length=50, verbose_name='В каком компании получил опыт работы')),
                ('year', models.IntegerField(verbose_name='Год получения')),
                ('description', models.CharField(max_length=50, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Звание',
            },
        ),
    ]
