# Generated by Django 4.2.7 on 2024-09-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_expirience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expirience',
            options={'verbose_name_plural': 'Опыт работы'},
        ),
    ]
