# Generated by Django 4.2.7 on 2024-09-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_alter_expirience_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Звание')),
                ('mini_title', models.CharField(max_length=50, verbose_name='В каком учреждении я получил образование')),
                ('year', models.IntegerField(verbose_name='Год получения')),
                ('description', models.CharField(max_length=50, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Образование',
            },
        ),
    ]
