# Generated by Django 4.2.7 on 2024-09-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0018_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100, verbose_name='Скилл')),
                ('percent', models.IntegerField(max_length=100, verbose_name='Владение скиллом в процентах')),
            ],
            options={
                'verbose_name_plural': 'Скилл',
            },
        ),
    ]
