# Generated by Django 4.2.7 on 2024-09-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='icon/', verbose_name='Фото 1')),
                ('title', models.CharField(max_length=100, verbose_name='Скилл')),
                ('description', models.CharField(max_length=155, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Проект',
            },
        ),
        migrations.AlterField(
            model_name='awards',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='expirience',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
    ]
