# Generated by Django 4.2.7 on 2024-09-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_project_alter_awards_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название проекта'),
        ),
    ]
