# Generated by Django 4.2.7 on 2024-09-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0021_alter_project_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('is_1', models.BooleanField(default=False, verbose_name='Разовый контракт')),
                ('is_2', models.BooleanField(default=False, verbose_name='Гибкий контракт')),
                ('is_3', models.BooleanField(default=False, verbose_name='Исходные файлы')),
                ('is_4', models.BooleanField(default=False, verbose_name='Поддержка')),
                ('is_5', models.BooleanField(default=False, verbose_name='Обновления')),
            ],
            options={
                'verbose_name_plural': 'Прайс план',
            },
        ),
    ]
