# Generated by Django 4.2.7 on 2024-09-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0022_priceplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quot', models.CharField(max_length=100, verbose_name='Цитата')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('company', models.CharField(max_length=50, verbose_name='Из какой компании автор')),
                ('image', models.ImageField(upload_to='image_author/', verbose_name='Фото Автора')),
            ],
            options={
                'verbose_name_plural': 'Цитату',
            },
        ),
    ]
