# Generated by Django 4.2.7 on 2024-09-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0023_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=155, verbose_name='Локация')),
                ('phone', models.IntegerField(max_length=155, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=155, verbose_name='Email')),
            ],
            options={
                'verbose_name_plural': 'Контакт',
            },
        ),
        migrations.AlterModelOptions(
            name='quotes',
            options={'verbose_name_plural': 'Цитата'},
        ),
        migrations.AlterField(
            model_name='quotes',
            name='quot',
            field=models.CharField(max_length=775, verbose_name='Цитата'),
        ),
    ]
