# Generated by Django 4.2.7 on 2024-09-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0024_contactme_alter_quotes_options_alter_quotes_quot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Фото')),
            ],
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_name_studio',
            field=models.CharField(default=1, max_length=155, verbose_name='Название студии'),
            preserve_default=False,
        ),
    ]
