# Generated by Django 5.1 on 2024-09-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0025_blog_settings_footer_name_studio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
